[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@synthetixio/main=lib/synthetix-v3/protocol/synthetix",
    "@synthetixio/core-contracts=lib/synthetix-v3/utils/core-contracts",
    "ds-test=lib/ds-test/src",
]

fs_permissions = [{ access = "read", path = "./" }]

[profile.lite]
optimizer = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
